package main

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"testing"
)

// Overlapping, near-square native assets exceed 64 MiB at the requested size.
// Odd heights also catch rounding mismatches that can cause endless redecodes.
func browserHeavyScene(t *testing.T, s *Server) {
	t.Helper()
	var assets []Asset
	for i := 0; i < 80; i++ {
		img := image.NewRGBA(image.Rect(0, 0, 512, 509))
		for y := 0; y < 509; y++ {
			for x := 0; x < 512; x++ {
				img.SetRGBA(x, y, color.RGBA{uint8(i + 20), uint8(x * 7), uint8(y * 7), 255})
			}
		}
		var buf bytes.Buffer
		png.Encode(&buf, img)
		a, err := prepare(s.root, buf.Bytes(), "token")
		if err != nil {
			t.Fatal(err)
		}
		assets = append(assets, a)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, ss := range s.sessions {
		var scene *Scene
		for _, candidate := range ss.Scenes {
			if candidate.Published && len(candidate.Elements) > 0 {
				scene = candidate
				break
			}
		}
		if scene == nil {
			t.Fatal("browser scene with map not found")
		}
		floorID := firstFloorID(scene)
		centerX, centerY := 0.0, 0.0
		if bounds := scene.Floors[floorID].RenderBounds; bounds != nil {
			aabb := polygonBounds(*bounds)
			centerX, centerY = (aabb.MinX+aabb.MaxX)/2, (aabb.MinY+aabb.MaxY)/2
		} else {
			initialized := false
			var minX, minY, maxX, maxY float64
			for _, element := range scene.Elements {
				if element.FloorID == floorID {
					left, top, right, bottom := element.Transform.X, element.Transform.Y, element.Transform.X+element.Transform.Width, element.Transform.Y+element.Transform.Height
					if !initialized {
						minX, minY, maxX, maxY, initialized = left, top, right, bottom, true
					} else {
						minX, minY = min(minX, left), min(minY, top)
						maxX, maxY = max(maxX, right), max(maxY, bottom)
					}
				}
			}
			if initialized {
				centerX, centerY = (minX+maxX)/2, (minY+maxY)/2
			}
		}
		for i, a := range assets {
			ss.Assets[a.ID] = a
			tokenID := id()
			scene.Tokens[tokenID] = Token{ID: tokenID, Name: "Cache", FloorID: floorID, X: centerX + float64(i%10), Y: centerY + float64(i/10), Size: 1024, Color: "#c2d89b", Asset: a.ID}
		}
		scene.Revision++
		s.dirty = true
		s.publishSceneSnapshot(ss, scene.ID)
	}
}

const browserDraftScenario = `(async()=>{
 const wait=async f=>{for(let i=0;i<200;i++){if(f())return;await new Promise(r=>setTimeout(r,50))}throw Error('draft test timeout')};
 const creds=JSON.parse(localStorage.getItem('atlas-sessions'))[0];
 const row=[...document.querySelectorAll('.token-row')].find(r=>r.textContent.includes('Browser hero'));row.click();window.heroID=row.dataset.tokenId;
 const field=document.getElementById('tokenName');field.value='Unsaved draft';field.dispatchEvent(new Event('input',{bubbles:true}));
 const joined=await fetch('/api/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:creds.session,invite:creds.invite,name:'Remote'})}).then(r=>r.json());
 const ws=new WebSocket(location.origin.replace('http','ws')+'/ws');window.remoteSocket=ws;window.remoteMessages=[];
 ws.onmessage=e=>window.remoteMessages.push(JSON.parse(e.data));await new Promise(r=>ws.onopen=r);ws.send(JSON.stringify(joined));await wait(()=>remoteMessages.some(m=>m.type==='campaignSnapshot'));const remoteHome=remoteMessages.find(m=>m.type==='campaignSnapshot'),remoteScene=remoteHome.scenes[0].id;ws.send(JSON.stringify({type:'subscribe',sceneId:remoteScene}));await wait(()=>remoteMessages.some(m=>m.type==='snapshot'));ws.send(JSON.stringify({type:'view',sceneId:remoteScene,region:{left:-10000,top:-10000,right:10000,bottom:10000}}));await wait(()=>remoteMessages.filter(m=>m.type==='snapshot').length>=2);
 await wait(()=>document.getElementById('tokenOwner').options.length===2);
 if(field.value!=='Unsaved draft')throw Error('snapshot erased draft');
 const gm=new WebSocket(location.origin.replace('http','ws')+'/ws');window.secondGM=gm;window.gmMessages=[];gm.onmessage=e=>gmMessages.push(JSON.parse(e.data));await new Promise(r=>gm.onopen=r);gm.send(JSON.stringify(creds));await wait(()=>gmMessages.some(m=>m.type==='campaignSnapshot'));const gmHome=gmMessages.find(m=>m.type==='campaignSnapshot'),gmScene=gmHome.scenes.find(s=>s.published).id;gm.send(JSON.stringify({type:'subscribe',sceneId:gmScene}));await wait(()=>gmMessages.some(m=>m.type==='snapshot'));gm.send(JSON.stringify({type:'view',sceneId:gmScene,region:{left:-10000,top:-10000,right:10000,bottom:10000}}));await wait(()=>gmMessages.filter(m=>m.type==='snapshot').length>=2);
 const player=remoteMessages.find(m=>m.type==='snapshot').you.id;
 const gmSnapshot=gmMessages.filter(m=>m.type==='snapshot').at(-1),elementRow=[...document.querySelectorAll('.tree-element-row')].find(row=>gmSnapshot?.elements?.[row.dataset.elementId]),elementID=elementRow?.dataset.elementId,remoteElement=gmSnapshot?.elements?.[elementID];if(!elementRow||!remoteElement)throw Error('loaded map element row missing');gm.send(JSON.stringify({type:'elementPreview',element:{id:elementID,transform:{...remoteElement.transform,x:remoteElement.transform.x+1}}}));
 gm.send(JSON.stringify({type:'properties',token:{id:heroID},properties:{owner:player,color:'#c2d89b'}}));await wait(()=>document.getElementById('tokenOwner').value===player);
 if(document.querySelector('[data-element-id="'+elementID+'"]')!==elementRow)throw Error('transform rebuilt scene tree');
 if(field.value!=='Unsaved draft')throw Error('property event erased draft');
 ws.send(JSON.stringify({type:'move',token:{id:heroID,x:700,y:500}}));await wait(()=>remoteMessages.some(m=>m.type==='move'&&m.id===heroID&&m.x===700));
 if(!document.querySelector('[data-token-id="'+heroID+'"]')){document.getElementById('fit').click();await wait(()=>document.querySelector('[data-token-id="'+heroID+'"]'));}const draftRow=document.querySelector('[data-token-id="'+heroID+'"]');if(!draftRow.classList.contains('selected'))draftRow.click();await wait(()=>field.value==='Unsaved draft');document.getElementById('properties').requestSubmit();await wait(()=>[...document.querySelectorAll('.token-row')].some(row=>row.textContent.includes('Unsaved draft')));
 ws.send(JSON.stringify({type:'final',client:'browser-player',seq:1,token:{id:heroID,x:800,y:600}}));await wait(()=>remoteMessages.some(m=>m.type==='ack'));
 document.getElementById('reconnect').click();await new Promise(r=>setTimeout(r,1500));await wait(()=>document.getElementById('connection').textContent.includes('В сети'));
 document.getElementById('toScenes').click();await wait(()=>!document.getElementById('campaignHome').hidden);const oldPrompt=window.prompt;window.prompt=()=> 'Reconnect rename';const published=[...document.querySelectorAll('.scene-card')].find(card=>card.classList.contains('published'));[...published.querySelectorAll('button')].find(button=>button.textContent==='Переименовать').click();document.getElementById('reconnect').click();window.prompt=oldPrompt;await wait(()=>document.getElementById('connection').textContent.includes('В сети'));await wait(()=>[...document.querySelectorAll('.scene-card')].some(card=>card.textContent.includes('Reconnect rename')));[...document.querySelectorAll('.scene-card')].find(card=>card.textContent.includes('Reconnect rename')).querySelector('.primary').click();await wait(()=>!document.getElementById('workspace').hidden);
 await wait(()=>document.querySelector('[data-token-id="'+heroID+'"]'));document.querySelector('[data-token-id="'+heroID+'"]').click();document.getElementById('board').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));
 const bounds=document.getElementById('board').getBoundingClientRect();return {x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2};
})()`

const browserModuleScenario = `(async()=>{
 const {Outbox,Drafts,CacheWriteBudget,blockedMoveCorrection,imageEdge}=await import('/reliability.js');const values=new Map();const store={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};const sent=[];
 const {SpatialIndex,ArtworkCache,LimitedMap,MetadataTouchTracker,decodedSize,fitImageSize,fitPlansToBudget,resolveImageMemoryBudgetMiB,planLRUEviction}=await import('/rendering.js');
	const {FloorRenderBoundsPathCache,FloorRenderBoundsResourceCache,FloorWalkableOverlayPathCache,SceneRenderIndex,abortUnwantedImageLoads,clipFloorRenderBounds,compositeFloors,drawPlayerWalkableOverlay,drawSceneStack,elementHandleAt,elementIntersectsView,floorCameraBounds,hitElement,pointInPlayableArea,pointInRenderBounds,renderBoundsAABB,tileAvailable,tiledFallbackCandidates,transformedFromDrag}=await import('/scene-content.js');
 const {drawTokens}=await import('/token-renderer.js');
 const {SceneTreeRuntime}=await import('/scene-tree.js');
 const {needsActiveTokenRequest}=await import('/scenes.js');
 const {canMoveTokenSegment,constrainTokenMovement}=await import('/movement-geometry.js');

 const playableState={floors:{floor:{id:'floor',walkableMode:'restricted',walkableComponents:[{id:'main',polygon:{outer:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}],holes:[[{x:40,y:40},{x:60,y:40},{x:60,y:60},{x:40,y:60}]]}}],renderBounds:{outer:[{x:0,y:0},{x:80,y:0},{x:80,y:80},{x:0,y:80}],holes:[]}}}};if(!pointInPlayableArea(playableState,'floor',20,20)||pointInPlayableArea(playableState,'floor',50,50)||pointInPlayableArea(playableState,'floor',90,20))throw Error('playable point predicate');
 const overlayCanvas=document.createElement('canvas');overlayCanvas.width=100;overlayCanvas.height=100;const overlayCtx=overlayCanvas.getContext('2d'),overlayPaths=new FloorWalkableOverlayPathCache(),overlayFloor={id:'floor',geometryRevision:1,showWalkableToPlayers:true,walkableMode:'restricted',renderBounds:{outer:[{x:0,y:0},{x:80,y:0},{x:80,y:80},{x:0,y:80}],holes:[]},walkableComponents:[{id:'main',polygon:{outer:[{x:10,y:10},{x:95,y:10},{x:95,y:95},{x:10,y:95}],holes:[[{x:30,y:30},{x:50,y:30},{x:50,y:50},{x:30,y:50}]]}}]},overlayState={scene:{id:'overlay'},floors:{floor:overlayFloor}};if(!drawPlayerWalkableOverlay(overlayCtx,overlayState,'floor',{scale:1},overlayPaths))throw Error('player walkable overlay was not drawn');const overlayPixel=(x,y)=>overlayCtx.getImageData(x,y,1,1).data;if(overlayPixel(5,5)[3]===0||overlayPixel(40,40)[3]===0||overlayPixel(20,20)[3]!==0||overlayPixel(90,90)[3]!==0)throw Error('player walkable overlay did not render render-bounds minus walkable geometry');drawPlayerWalkableOverlay(overlayCtx,overlayState,'floor',{scale:1},overlayPaths);if(overlayPaths.builds!==1)throw Error('player walkable overlay path was rebuilt without a geometry change');overlayFloor.geometryRevision=2;drawPlayerWalkableOverlay(overlayCtx,overlayState,'floor',{scale:1},overlayPaths);if(overlayPaths.builds!==2||drawPlayerWalkableOverlay(overlayCtx,{scene:{id:'overlay'},floors:{floor:{...overlayFloor,showWalkableToPlayers:false}}},'floor',{scale:1},overlayPaths))throw Error('player walkable overlay ignored visibility or geometry revision');
 const rect=(left,top,right,bottom)=>({outer:[{x:left,y:top},{x:right,y:top},{x:right,y:bottom},{x:left,y:bottom}],holes:[]}),movementState={floors:{floor:{id:'floor',geometryRevision:1,walkableMode:'restricted',walkableComponents:[{id:'main',polygon:{...rect(0,0,100,100),holes:[rect(40,40,60,60).outer]}}]}}};
 if(!canMoveTokenSegment(movementState,'floor',{x:10,y:10},{x:30,y:30})||canMoveTokenSegment(movementState,'floor',{x:10,y:50},{x:90,y:50}))throw Error('client movement hole validation');
 movementState.floors.floor={id:'floor',geometryRevision:2,walkableMode:'restricted',walkableComponents:[{id:'left',polygon:rect(0,0,40,40)},{id:'right',polygon:rect(60,0,100,40)}]};if(canMoveTokenSegment(movementState,'floor',{x:20,y:20},{x:80,y:20}))throw Error('client movement crossed separate components');
 movementState.floors.floor={id:'floor',geometryRevision:3,walkableMode:'restricted',walkableComponents:[{id:'left',polygon:rect(0,0,50,50)},{id:'right',polygon:rect(50,0,100,50)}]};if(!canMoveTokenSegment(movementState,'floor',{x:25,y:25},{x:75,y:25}))throw Error('client movement rejected shared edge');
 movementState.floors.floor={id:'floor',geometryRevision:4,walkableMode:'restricted',walkableComponents:[{id:'left',polygon:rect(0,0,50,50)},{id:'right',polygon:rect(50,50,100,100)}]};if(canMoveTokenSegment(movementState,'floor',{x:25,y:25},{x:75,y:75}))throw Error('client movement crossed point contact');
 movementState.floors.floor={id:'floor',geometryRevision:5,walkableMode:'unrestricted',walkableComponents:[],renderBounds:{outer:[{x:0,y:0},{x:100,y:0},{x:100,y:30},{x:30,y:30},{x:30,y:100},{x:0,y:100}],holes:[]}};if(canMoveTokenSegment(movementState,'floor',{x:15,y:80},{x:80,y:15}))throw Error('client movement crossed concave render bounds');
 movementState.floors.floor={id:'floor',geometryRevision:6,walkableMode:'restricted',walkableComponents:[{id:'main',polygon:rect(0,0,100,100)}]};let constrained=constrainTokenMovement(movementState,'floor',{x:20,y:50},{x:120,y:80});if(Math.abs(constrained.x-99.998)>1e-6||Math.abs(constrained.y-80)>1e-6||!canMoveTokenSegment(movementState,'floor',{x:20,y:50},constrained))throw Error('walkable wall did not slide');
 movementState.floors.floor={id:'floor',geometryRevision:7,walkableMode:'restricted',walkableComponents:[{id:'main',polygon:{...rect(0,0,100,100),holes:[rect(40,40,60,60).outer]}}]};constrained=constrainTokenMovement(movementState,'floor',{x:20,y:50},{x:80,y:70});if(Math.abs(constrained.x-39.998)>1e-6||Math.abs(constrained.y-60)>1e-6||!canMoveTokenSegment(movementState,'floor',{x:20,y:50},constrained))throw Error('walkable hole did not slide: '+JSON.stringify(constrained));if(!canMoveTokenSegment(movementState,'floor',constrained,{x:80,y:70}))throw Error('walkable hole slide could not continue around corner: '+JSON.stringify(constrained));
 movementState.floors.floor={id:'floor',geometryRevision:8,walkableMode:'restricted',walkableComponents:[{id:'left',polygon:rect(0,0,40,40)},{id:'right',polygon:rect(60,0,100,40)}]};constrained=constrainTokenMovement(movementState,'floor',{x:20,y:20},{x:80,y:20});if(Math.abs(constrained.x-39.998)>1e-6||Math.abs(constrained.y-20)>1e-6)throw Error('slide jumped across separate components');
 movementState.floors.floor={id:'floor',geometryRevision:9,walkableMode:'unrestricted',walkableComponents:[],renderBounds:rect(0,0,100,100)};constrained=constrainTokenMovement(movementState,'floor',{x:50,y:20},{x:80,y:-20});if(Math.abs(constrained.x-80)>1e-6||Math.abs(constrained.y-.002)>1e-6||!canMoveTokenSegment(movementState,'floor',{x:50,y:20},constrained))throw Error('render bounds wall did not slide');
 movementState.floors.floor={id:'floor',geometryRevision:10,walkableMode:'restricted',walkableComponents:[{id:'left',polygon:rect(0,0,50,50)},{id:'right',polygon:rect(50,50,100,100)}]};constrained={x:25,y:25};for(let i=0;i<4;i++){const prior=constrained;constrained=constrainTokenMovement(movementState,'floor',prior,{x:75,y:75});if(constrained.x>=50&&constrained.y>=50||!canMoveTokenSegment(movementState,'floor',prior,constrained))throw Error('repeated slide crossed a point contact: '+JSON.stringify({prior,constrained}));}
 movementState.floors.floor={id:'floor',geometryRevision:11,walkableMode:'restricted',walkableComponents:[{id:'left',polygon:rect(0,0,60,100)},{id:'right',polygon:rect(50,0,100,100)}]};constrained=constrainTokenMovement(movementState,'floor',{x:20,y:50},{x:120,y:80});if(Math.abs(constrained.x-99.998)>1e-6||Math.abs(constrained.y-80)>1e-6)throw Error('slide stopped on an internal component edge');
 movementState.floors.floor={id:'floor',geometryRevision:12,walkableMode:'unrestricted',walkableComponents:[],renderBounds:{outer:[{x:0,y:0},{x:100,y:0},{x:100,y:30},{x:30,y:30},{x:30,y:100},{x:0,y:100}],holes:[]}};constrained=constrainTokenMovement(movementState,'floor',{x:15,y:80},{x:80,y:15});if(Math.hypot(constrained.x-30,constrained.y-30)>.0021||!canMoveTokenSegment(movementState,'floor',{x:15,y:80},constrained))throw Error('concave render bounds corner did not slide');
 movementState.floors.floor={id:'floor',geometryRevision:13,walkableMode:'restricted',walkableComponents:[{id:'slope',polygon:{outer:[{x:0,y:0},{x:100,y:37},{x:100,y:100},{x:0,y:100}],holes:[]}}]};const slopeLength=Math.hypot(100,37),outward={x:37/slopeLength,y:-100/slopeLength},inward={x:-outward.x,y:-outward.y};constrained={x:10+inward.x*10,y:3.7+inward.y*10};let priorAlong=-Infinity;for(let step=2;step<=8;step++){const edgePoint={x:step*10,y:step*3.7},target={x:edgePoint.x+outward.x*20,y:edgePoint.y+outward.y*20},prior=constrained;constrained=constrainTokenMovement(movementState,'floor',prior,target);const along=(constrained.x*100+constrained.y*37)/(slopeLength*slopeLength),signedInset=(100*constrained.y-37*constrained.x)/slopeLength;if(!canMoveTokenSegment(movementState,'floor',prior,constrained)||along<=priorAlong||Math.abs(along-step/10)>.0001||signedInset<.001||signedInset>.003)throw Error('diagonal wall slide jittered: '+JSON.stringify({step,prior,constrained,along,signedInset}));priorAlong=along;}
 movementState.floors.floor={id:'floor',geometryRevision:14,walkableMode:'unrestricted',walkableComponents:[],renderBounds:{outer:[{x:0,y:0},{x:100,y:37},{x:100,y:100},{x:0,y:100}],holes:[]}};constrained={x:10+inward.x*10,y:3.7+inward.y*10};priorAlong=-Infinity;for(let step=2;step<=8;step++){const edgePoint={x:step*10,y:step*3.7},target={x:edgePoint.x+outward.x*20,y:edgePoint.y+outward.y*20},prior=constrained;constrained=constrainTokenMovement(movementState,'floor',prior,target);const along=(constrained.x*100+constrained.y*37)/(slopeLength*slopeLength),signedInset=(100*constrained.y-37*constrained.x)/slopeLength;if(!canMoveTokenSegment(movementState,'floor',prior,constrained)||along<=priorAlong||Math.abs(along-step/10)>.0001||signedInset<.001||signedInset>.003)throw Error('diagonal render bounds slide jittered: '+JSON.stringify({step,prior,constrained,along,signedInset}));priorAlong=along;}
 movementState.floors.floor={id:'floor',geometryRevision:15,walkableMode:'unrestricted',walkableComponents:[],renderBounds:{outer:[{x:0,y:0},{x:100,y:0},{x:100,y:30},{x:30,y:30},{x:30,y:100},{x:0,y:100}],holes:[]}};constrained={x:15,y:80};const cornerTarget={x:80,y:15};for(let step=0;step<2;step++){const prior=constrained;constrained=constrainTokenMovement(movementState,'floor',prior,cornerTarget);if(!canMoveTokenSegment(movementState,'floor',prior,constrained)||Math.hypot(constrained.x-cornerTarget.x,constrained.y-cornerTarget.y)>=Math.hypot(prior.x-cornerTarget.x,prior.y-cornerTarget.y))throw Error('single contour corner slide stuck: '+JSON.stringify({step,prior,constrained}));}if(Math.hypot(constrained.x-cornerTarget.x,constrained.y-cornerTarget.y)>.003)throw Error('single contour corner slide did not turn: '+JSON.stringify(constrained));
 movementState.floors.floor={id:'floor',geometryRevision:16,walkableMode:'restricted',walkableComponents:[{id:'walkable',polygon:rect(0,30,100,100)}],renderBounds:{outer:[{x:0,y:50},{x:100,y:0},{x:100,y:100},{x:0,y:100}],holes:[]}};const mixedCornerFrom={x:70,y:40},mixedCornerTarget={x:10,y:10};constrained=constrainTokenMovement(movementState,'floor',mixedCornerFrom,mixedCornerTarget);if(!canMoveTokenSegment(movementState,'floor',mixedCornerFrom,constrained)||constrained.x>=35||constrained.y<=30||Math.hypot(constrained.x-mixedCornerTarget.x,constrained.y-mixedCornerTarget.y)>=Math.hypot(mixedCornerFrom.x-mixedCornerTarget.x,mixedCornerFrom.y-mixedCornerTarget.y))throw Error('walkable/render corner slide stuck: '+JSON.stringify(constrained));
 const floorState={floors:{lower:{id:'lower',order:0,opacity:.6,opacityWhenViewedFromBelow:0},upper:{id:'upper',order:1,opacity:.8,opacityWhenViewedFromBelow:.5}}};const fromBelow=compositeFloors(floorState,'lower'),fromAbove=compositeFloors(floorState,'upper');if(fromBelow.map(v=>v.floor.id).join(',')!=='lower,upper'||fromBelow[1].alpha!==.4||fromAbove.map(v=>v.floor.id).join(',')!=='lower,upper'||fromAbove[1].alpha!==.8)throw Error('floor compositing');floorState.floors.upper.opacityWhenViewedFromBelow=0;if(compositeFloors(floorState,'lower').length!==1)throw Error('zero-alpha floor loaded');
 const active={id:'active',floorId:'lower'};if(needsActiveTokenRequest(active,false,'active','lower',null)||!needsActiveTokenRequest(active,true,'active','lower',null)||!needsActiveTokenRequest(active,false,'other','lower',null)||!needsActiveTokenRequest(active,false,'active','upper',null)||!needsActiveTokenRequest(active,false,'active','lower',{}))throw Error('active token request fast path');
 const transformBase={x:10,y:20,width:100,height:50,rotation:0,pointerX:60,pointerY:-8};
 const moved=transformedFromDrag(transformBase,'move',15,-5);if(moved.x!==25||moved.y!==15)throw Error('element move transform');
 const proportional=transformedFromDrag(transformBase,'se',50,10);if(proportional.width!==150||proportional.height!==75)throw Error('element aspect transform');
 const resized=transformedFromDrag(transformBase,'se',50,10,true);if(resized.width!==150||resized.height!==60)throw Error('element resize transform');
 const rotated=transformedFromDrag(transformBase,'rotate',50,53);if(Math.abs(rotated.rotation-90)>.001)throw Error('element rotate transform');
 const handlesElement={transform:transformBase};if(elementHandleAt(handlesElement,60,-8,1,false)==='rotate'||elementHandleAt(handlesElement,60,-8,1,true)!=='rotate')throw Error('base rotation handle policy');
 const sparseAsset={tilePresence:'AQ==.AA=='};if(!tileAvailable(sparseAsset,0,0,0,1)||tileAvailable(sparseAsset,1,0,0,1))throw Error('sparse tile manifest');
 const small=decodedSize(32,16,512);if(small.width!==32||small.height!==16)throw Error('small asset upscaled');
 const narrow=decodedSize(512,113,128);if(narrow.width!==128||narrow.height!==28)throw Error('aspect ratio changed');
 const odd=fitImageSize(512,509,256);if(odd.width!==256||odd.height!==255)throw Error('odd size rounding');
 const budget=56*1048576,many=Array.from({length:2000},()=>({plan:{width:512,height:509,native:{width:512,height:509}}})),planned=fitPlansToBudget(many,budget);if(planned>budget)throw Error('plan budget exceeded');if(many.some(({plan})=>plan.width>512||plan.height>509||plan.width<1||plan.height<1))throw Error('invalid planned decode size');
 if(resolveImageMemoryBudgetMiB(undefined)!==128||resolveImageMemoryBudgetMiB(2)!==64||resolveImageMemoryBudgetMiB(4)!==64||resolveImageMemoryBudgetMiB(8)!==128||resolveImageMemoryBudgetMiB(16)!==256||resolveImageMemoryBudgetMiB(64)!==256)throw Error('auto image budget profile');
 if(resolveImageMemoryBudgetMiB(2,'512')!==512||resolveImageMemoryBudgetMiB(64,'64')!==64||resolveImageMemoryBudgetMiB(2,'bogus')!==64)throw Error('manual image budget override');
 const stale=new Map([['old',{size:90,used:-1}]]);if(planLRUEviction(stale,new Set(),90,100).keys.length)throw Error('age-only image eviction');
 const lruEntries=new Map([['visible',{size:30,used:1}],['old',{size:30,used:2}],['new',{size:30,used:3}]]),lru=planLRUEviction(lruEntries,new Set(['visible']),120,100);if(lru.keys.join(',')!=='old,new'||lru.remaining>85)throw Error('LRU/wanted hysteresis');
 const shrunk=planLRUEviction(lruEntries,new Set(),90,64);if(shrunk.keys.join(',')!=='visible,old'||shrunk.remaining>Math.floor(64*.85))throw Error('reduced image budget eviction');
 const boundedEntries=new Map(Array.from({length:100},(_,i)=>[String(i),{size:10,used:i}])),bounded=planLRUEviction(boundedEntries,new Set(),1000,100);if(bounded.remaining>85||bounded.keys.length===0)throw Error('image cache is not bounded under pressure');
 const progressive=planLRUEviction(new Map([['scaled',{size:100,bitmapSize:80,fallback:{size:20},used:1}]]),new Set(),100,80);if(progressive.degradeKeys.join(',')!=='scaled'||progressive.keys.length||progressive.remaining!==20)throw Error('image degradation did not precede eviction');
 const index=new SpatialIndex();for(let i=0;i<2000;i++)index.set({id:String(i),x:i*100,y:0,size:40});if(index.query(-30,-30,30,30).length!==1)throw Error('spatial query');index.set({id:'0',x:-1000,y:0,size:40});if(index.query(-30,-30,30,30).length)throw Error('stale spatial position');index.remove('0');if(index.query(-1100,-50,-900,50).length)throw Error('spatial delete');
 const limited=new LimitedMap(2);limited.set('a',1).set('b',2).set('c',3);if(limited.size!==2||limited.has('a')||limited.get('c')!==3)throw Error('metadata map is not bounded');
 const touches=new MetadataTouchTracker(2,60000);if(!touches.due('asset',100000))throw Error('first metadata touch not due');touches.record('asset',100000);if(touches.due('asset',159999)||!touches.due('asset',160001))throw Error('metadata touch interval');touches.record('b',100000);touches.record('c',100000);if(touches.size!==2||!touches.due('asset',100001))throw Error('metadata touch tracker is not bounded');
 const renderState={elements:{a:{id:'a',floorId:'lower',layerId:'visual',zOrder:2,visible:true,opacity:1,transform:{x:0,y:0,width:20,height:20,rotation:0}},b:{id:'b',floorId:'lower',layerId:'visual',zOrder:1,visible:true,opacity:1,transform:{x:30,y:0,width:20,height:20,rotation:0}}}};
 const renderIndex=new SceneRenderIndex();if(renderIndex.forLayer(renderState,'visual').join(',')!=='b,a')throw Error('render index order');const rebuilds=renderIndex.rebuilds,oldA=renderState.elements.a;renderState.elements.a={...oldA,transform:{...oldA.transform,x:10}};renderIndex.elementChanged(oldA,renderState.elements.a);if(renderState.elements[renderIndex.forLayer(renderState,'visual')[1]].transform.x!==10||renderIndex.rebuilds!==rebuilds)throw Error('transform invalidated render order');const movedA={...renderState.elements.a,zOrder:0};renderState.elements.a=movedA;renderIndex.elementChanged(oldA,movedA);if(renderIndex.forLayer(renderState,'visual')[0]!=='a'||renderIndex.rebuilds===rebuilds)throw Error('render order change not invalidated');renderIndex.reset();renderState.elements={b:renderState.elements.b};if(renderIndex.forLayer(renderState,'visual').join(',')!=='b')throw Error('scene switch retained elements');
 if(!elementIntersectsView({transform:{x:90,y:90,width:100,height:40,rotation:45}},{left:100,top:100,right:160,bottom:160})||elementIntersectsView({transform:{x:1000,y:1000,width:100,height:40,rotation:45}},{left:0,top:0,right:200,bottom:200}))throw Error('rotated bitmap viewport culling');
 const drawState={floors:{lower:{id:'lower',order:0,opacity:1,opacityWhenViewedFromBelow:0}},layers:{visual:{id:'visual',floorId:'lower',kind:'visual',order:0,visible:true,opacity:1}},elements:{far:{id:'far',floorId:'lower',layerId:'visual',zOrder:0,visible:true,opacity:1,assetId:'image',transform:{x:1000,y:1000,width:100,height:100,rotation:0}}},assets:{image:{id:'image',kind:'image',renderMode:'bitmap',width:100,height:100}}};let requests=0;const drawArgs={ctx:{globalAlpha:1},state:drawState,currentFloorId:'lower',view:{left:0,top:0,right:200,bottom:200},camera:{scale:1},dpr:1,requestImage:()=>{requests++;},editor:false,drawTokenLayer:()=>{},renderIndex:new SceneRenderIndex()};drawSceneStack(drawArgs);if(requests)throw Error('offscreen bitmap requested');drawState.floors.lower.opacity=0;drawState.elements.far={...drawState.elements.far,transform:{...drawState.elements.far.transform,x:20,y:20}};drawArgs.renderIndex.reset();drawSceneStack(drawArgs);if(requests)throw Error('zero-alpha floor requested bitmap');
	const clipCanvas=document.createElement('canvas');clipCanvas.width=80;clipCanvas.height=80;const clipCtx=clipCanvas.getContext('2d'),clipPaths=new FloorRenderBoundsPathCache(),clipFloor={id:'lower',order:0,opacity:1,opacityWhenViewedFromBelow:0,geometryRevision:1,renderBounds:{outer:[{x:0,y:0},{x:60,y:0},{x:60,y:20},{x:20,y:20},{x:20,y:60},{x:0,y:60}],holes:[]}},clipState={scene:{id:'clip-scene'},floors:{lower:clipFloor},layers:{visual:{id:'visual',floorId:'lower',kind:'visual',order:0,visible:true,opacity:1}},elements:{partial:{id:'partial',floorId:'lower',layerId:'visual',zOrder:0,visible:true,opacity:1,transform:{x:10,y:10,width:40,height:40,rotation:0}}},assets:{}};const clipArgs={ctx:clipCtx,state:clipState,currentFloorId:'lower',view:{left:0,top:0,right:80,bottom:80},camera:{scale:1},dpr:1,requestImage:()=>null,editor:false,drawTokenLayer:()=>{},renderIndex:new SceneRenderIndex(),renderBoundsPaths:clipPaths};drawSceneStack(clipArgs);if(!clipCtx.getImageData(15,15,1,1).data[3]||clipCtx.getImageData(40,40,1,1).data[3])throw Error('concave bounds did not clip partial element');
	const renderCameraBounds=floorCameraBounds(clipState,'lower');if(renderCameraBounds.left!==0||renderCameraBounds.top!==0||renderCameraBounds.right!==60||renderCameraBounds.bottom!==60)throw Error('camera did not use render bounds AABB');const contentCameraBounds=floorCameraBounds({...clipState,floors:{lower:{...clipFloor,renderBounds:null}}},'lower');if(contentCameraBounds.left!==10||contentCameraBounds.top!==10||contentCameraBounds.right!==50||contentCameraBounds.bottom!==50||renderBoundsAABB(null)!==null)throw Error('null render bounds camera fallback');
 if(!pointInRenderBounds(clipState,'lower',60,10)||pointInRenderBounds(clipState,'lower',40,40)||!pointInRenderBounds({floors:{lower:{id:'lower'}}},'lower',400,400))throw Error('render bounds hit gate');const hitIndex=new SceneRenderIndex();if(!hitElement(clipState,'lower',40,40,hitIndex)||pointInRenderBounds(clipState,'lower',40,40))throw Error('GM outside-bounds element access was lost');const hitTokens=new SpatialIndex();hitTokens.set({id:'outside',x:40,y:40,size:20});if(!hitTokens.query(40,40,40,40).length||pointInRenderBounds(clipState,'lower',40,40))throw Error('player token hit was not gated before spatial candidates');
 clipCtx.clearRect(0,0,80,80);clipState.layers.tokens={id:'tokens',floorId:'lower',kind:'tokens',order:1};clipArgs.drawTokenLayer=()=>{clipCtx.fillStyle='#00f';clipCtx.fillRect(0,0,80,80);};drawSceneStack(clipArgs);if(!clipCtx.getImageData(10,40,1,1).data[3]||clipCtx.getImageData(40,40,1,1).data[3])throw Error('token layer escaped render bounds clip');
	clipCtx.clearRect(0,0,80,80);clipCtx.save();clipFloorRenderBounds(clipCtx,clipState,clipFloor,clipPaths);clipCtx.fillStyle='#fff';clipCtx.fillRect(0,0,80,80);clipCtx.restore();if(!clipCtx.getImageData(10,40,1,1).data[3]||clipCtx.getImageData(40,40,1,1).data[3])throw Error('grid/world-effect clip helper failed');const firstBuilds=clipPaths.builds;clipCtx.clearRect(0,0,80,80);clipFloor.geometryRevision=2;clipFloor.renderBounds={outer:[{x:30,y:30},{x:70,y:30},{x:70,y:70},{x:30,y:70}],holes:[]};clipPaths.syncState(clipState);if(clipPaths.entries.size)throw Error('stale render bounds path survived snapshot invalidation');clipCtx.save();clipFloorRenderBounds(clipCtx,clipState,clipFloor,clipPaths);clipCtx.fillRect(0,0,80,80);clipCtx.restore();if(clipPaths.builds!==firstBuilds+1||clipCtx.getImageData(10,10,1,1).data[3]||!clipCtx.getImageData(40,40,1,1).data[3])throw Error('render bounds path cache ignored geometry revision');clipCtx.clearRect(0,0,80,80);drawSceneStack({...clipArgs,editor:true});if(!clipCtx.getImageData(25,25,1,1).data[3])throw Error('GM editor was clipped to render bounds');
	const tiledAsset={id:'map',renderMode:'tiled',width:2048,height:2048,levels:3},fallbacks=tiledFallbackCandidates(tiledAsset,0,1,0);if(fallbacks[0]?.path!=='map/1_0_0.png'||fallbacks[0].cropX!==256||fallbacks[0].cropWidth!==256)throw Error('tiled fallback mapping');const drawCalls=[],fallbackCtx={globalAlpha:1,save(){},restore(){},translate(){},rotate(){},drawImage(...args){drawCalls.push(args);}},fallbackState={floors:{lower:{id:'lower',order:0,opacity:1,opacityWhenViewedFromBelow:0}},layers:{visual:{id:'visual',floorId:'lower',kind:'visual',order:0,visible:true,opacity:1}},elements:{map:{id:'map',floorId:'lower',layerId:'visual',zOrder:0,visible:true,opacity:1,assetId:'map',transform:{x:0,y:0,width:2048,height:2048,rotation:0}}},assets:{map:tiledAsset}};drawSceneStack({ctx:fallbackCtx,state:fallbackState,currentFloorId:'lower',view:{left:520,top:10,right:900,bottom:400},camera:{scale:2},dpr:1,requestImage:()=>null,peekImage:path=>path==='map/1_0_0.png'?{width:128,height:128}:null,editor:false,drawTokenLayer:()=>{},renderIndex:new SceneRenderIndex()});if(drawCalls.length!==1||drawCalls[0].length!==9||drawCalls[0][1]!==64||drawCalls[0][3]!==64||drawCalls[0][5]!==512)throw Error('coarse LOD was not cropped into missing detailed tile');
	const tileCanvas=document.createElement('canvas'),tileCtx=tileCanvas.getContext('2d'),tileRequests=[],tileBounds=new FloorRenderBoundsResourceCache(32),initialTileBounds={outer:[{x:50,y:50},{x:900,y:50},{x:900,y:400},{x:400,y:400},{x:400,y:900},{x:50,y:900}],holes:[]},tileFloor={id:'lower',order:0,opacity:1,opacityWhenViewedFromBelow:0,geometryRevision:1,renderBounds:initialTileBounds},tileState={scene:{id:'tile-bounds'},floors:{lower:tileFloor},layers:{visual:{id:'visual',floorId:'lower',kind:'visual',order:0,visible:true,opacity:1}},elements:{map:{id:'map',floorId:'lower',layerId:'visual',zOrder:0,visible:true,opacity:1,assetId:'map',transform:{x:0,y:0,width:2048,height:2048,rotation:0}}},assets:{map:tiledAsset}};const tileArgs={ctx:tileCtx,state:tileState,currentFloorId:'lower',view:{left:0,top:0,right:2048,bottom:2048},camera:{scale:1},dpr:1,requestImage:(path,edge,priority='visible')=>{tileRequests.push({path,priority});return null;},peekImage:()=>null,editor:false,drawTokenLayer:()=>{},renderIndex:new SceneRenderIndex(),resourceBounds:tileBounds};drawSceneStack(tileArgs);const requestedTiles=tileRequests.map(item=>item.path).sort().join(',');if(requestedTiles!=='map/0_0_0.png,map/0_0_1.png,map/0_1_0.png'||tileRequests.some(item=>item.priority==='prefetch'))throw Error('concave render bounds did not cull outside tile requests');const misses=tileBounds.misses;drawSceneStack(tileArgs);if(tileBounds.hits===0||tileBounds.misses!==misses)throw Error('tile bounds classifications were not cached');tileFloor.geometryRevision=2;tileFloor.renderBounds={outer:[{x:1100,y:1100},{x:1400,y:1100},{x:1400,y:1400},{x:1100,y:1400}],holes:[]};tileBounds.syncState(tileState);if(tileBounds.classifications.size||tileBounds.elements.size)throw Error('stale tile classification survived bounds revision');tileRequests.length=0;drawSceneStack(tileArgs);if(tileRequests.map(item=>item.path).join(',')!=='map/0_2_2.png')throw Error('tile wanted set used stale bounds');tileFloor.geometryRevision=3;tileFloor.renderBounds=initialTileBounds;tileBounds.syncState(tileState);tileRequests.length=0;drawSceneStack(tileArgs);if(tileRequests.map(item=>item.path).sort().join(',')!==requestedTiles)throw Error('tile classification did not recover after bounds restore');for(let revision=4;revision<44;revision++){tileFloor.geometryRevision=revision;tileFloor.renderBounds=revision%2?initialTileBounds:{outer:[{x:1100,y:1100},{x:1400,y:1100},{x:1400,y:1400},{x:1100,y:1400}],holes:[]};tileBounds.syncState(tileState);tileRequests.length=0;drawSceneStack(tileArgs);}if(tileBounds.classifications.size>32||tileBounds.elements.size>512||tileBounds.revisions.size!==1)throw Error('render bounds caches grew during frequent edits');
	const journeyAsset={id:'journey',renderMode:'tiled',width:8192,height:8192,levels:5},journeyFloor={id:'lower',order:0,opacity:1,opacityWhenViewedFromBelow:0,geometryRevision:1,renderBounds:{outer:[{x:0,y:0},{x:1536,y:0},{x:1536,y:512},{x:512,y:512},{x:512,y:1536},{x:0,y:1536}],holes:[]}},journeyState={scene:{id:'tile-journey'},floors:{lower:journeyFloor},layers:{visual:{id:'visual',floorId:'lower',kind:'visual',order:0,visible:true,opacity:1}},elements:{map:{id:'map',floorId:'lower',layerId:'visual',zOrder:0,visible:true,opacity:1,assetId:'journey',transform:{x:0,y:0,width:8192,height:8192,rotation:0}}},assets:{journey:journeyAsset}},journeyCache=new FloorRenderBoundsResourceCache(64),decodedTiles=new Set();let journeyRequests=0,journeyDecodes=0,journeyRAM=0;const journeyRender=view=>{let planned=0;drawSceneStack({ctx:tileCtx,state:journeyState,currentFloorId:'lower',view,camera:{scale:1},dpr:1,requestImage:path=>{planned++;if(!decodedTiles.has(path)){decodedTiles.add(path);journeyRequests++;journeyDecodes++;journeyRAM+=512*512*4;}return null;},peekImage:()=>null,editor:false,drawTokenLayer:()=>{},renderIndex:new SceneRenderIndex(),resourceBounds:journeyCache});return planned;};const insidePlans=journeyRender({left:0,top:0,right:1024,bottom:768}),insideRequests=journeyRequests,insideDecodes=journeyDecodes,insideRAM=journeyRAM,outsidePlans=journeyRender({left:2048,top:2048,right:3072,bottom:2816});if(!insidePlans||outsidePlans||journeyRequests!==insideRequests||journeyDecodes!==insideDecodes||journeyRAM!==insideRAM)throw Error('outside camera selected large-map resources');const returnPlans=journeyRender({left:0,top:0,right:1024,bottom:768});if(!returnPlans||journeyRequests!==insideRequests||journeyDecodes!==insideDecodes||journeyRAM!==insideRAM||journeyRAM>64*1048576)throw Error('inside/outside/back reloaded or leaked tiled resources: '+JSON.stringify({returnPlans,journeyRequests,insideRequests,journeyDecodes,insideDecodes,journeyRAM,insideRAM}));
	const keptController=new AbortController(),staleController=new AbortController(),pendingLoads=new Map([['kept',keptController],['stale',staleController]]);if(abortUnwantedImageLoads(pendingLoads,new Set(['kept']))!==1||keptController.signal.aborted||!staleController.signal.aborted||abortUnwantedImageLoads(pendingLoads,new Set(['kept']))!==0)throw Error('stale pending preload was not cancelled');
	const sharedBounds=new FloorRenderBoundsResourceCache(32),sharedFloor={id:'lower',order:0,opacity:1,opacityWhenViewedFromBelow:0,geometryRevision:1,renderBounds:{outer:[{x:0,y:0},{x:60,y:0},{x:60,y:20},{x:20,y:20},{x:20,y:60},{x:0,y:60}],holes:[]}},sharedState={scene:{id:'shared-bounds'},floors:{lower:sharedFloor},layers:{visual:{id:'visual',floorId:'lower',kind:'visual',order:0,visible:true,opacity:1}},elements:{partial:{id:'partial',floorId:'lower',layerId:'visual',zOrder:0,visible:true,opacity:1,assetId:'shared',transform:{x:10,y:10,width:40,height:40,rotation:0}},outside:{id:'outside',floorId:'lower',layerId:'visual',zOrder:1,visible:true,opacity:1,assetId:'shared',transform:{x:30,y:30,width:10,height:10,rotation:0}}},assets:{shared:{id:'shared',kind:'image',renderMode:'bitmap',width:40,height:40}}},sharedRequests=[];const sharedArgs={ctx:tileCtx,state:sharedState,currentFloorId:'lower',view:{left:0,top:0,right:80,bottom:80},camera:{scale:1},dpr:1,requestImage:path=>{sharedRequests.push(path);return null;},editor:false,drawTokenLayer:()=>{},renderIndex:new SceneRenderIndex(),resourceBounds:sharedBounds};drawSceneStack(sharedArgs);if(sharedRequests.join(',')!=='shared/image.png')throw Error('shared bitmap was not culled per usage');sharedRequests.length=0;drawSceneStack({...sharedArgs,editor:true});if(sharedRequests.length!==2)throw Error('GM bitmap resource culling was enabled');
	const tokenArtwork=new ArtworkCache(1048576),tokenIndex=new SpatialIndex(),tokenState={partial:{id:'partial',floorId:'lower',x:25,y:25,size:12,name:'partial',color:'#fff',asset:'portrait'},outside:{id:'outside',floorId:'lower',x:40,y:40,size:10,name:'outside',color:'#fff',asset:'portrait'}};for(const token of Object.values(tokenState))tokenIndex.set(token);const tokenRequests=[];drawTokens({ctx:tileCtx,camera:{x:0,y:0,scale:1},viewport:{w:80,h:80},dpr:1,tokens:tokenState,index:tokenIndex,visuals:new Map(),moving:new Set(),drag:null,selected:null,queue:[],requestImage:path=>{tokenRequests.push(path);return null;},artwork:tokenArtwork,delta:16,floorId:'lower',resourceVisible:(x,y,radius)=>sharedBounds.intersectsCircle(sharedState,sharedFloor,x,y,radius)});if(tokenRequests.join(',')!=='portrait/token.png')throw Error('shared token artwork was not culled per usage');tokenArtwork.clear();
	tileCtx.clearRect(0,0,tileCanvas.width,tileCanvas.height);const warningToken={id:'warning',floorId:'lower',x:40,y:40,size:20,name:'warning',color:'#fff',asset:''},warningIndex=new SpatialIndex();warningIndex.set(warningToken);const warningArtwork=new ArtworkCache(1048576);drawTokens({ctx:tileCtx,camera:{x:0,y:0,scale:1},viewport:{w:80,h:80},dpr:1,tokens:{warning:warningToken},index:warningIndex,visuals:new Map(),moving:new Set(),drag:null,selected:null,queue:[],requestImage:()=>null,artwork:warningArtwork,delta:16,floorId:'lower',outOfBounds:()=>true});const warningPixel=tileCtx.getImageData(55,40,1,1).data;if(warningPixel[0]<200||warningPixel[1]>160||warningPixel[2]>150||warningPixel[3]===0)throw Error('out-of-bounds token was not highlighted');warningArtwork.clear();
 const artwork=new ArtworkCache(16);artwork.begin(['a','b']);const a=artwork.get('a',2,2,()=>{});if(artwork.get('b',2,2,()=>{})!==null||artwork.get('a',2,2,()=>{})!==a)throw Error('visible artwork churn');artwork.clear();if(artwork.bytes!==0||a.width!==0)throw Error('artwork not released');
 const box=new Outbox(store,'test',cmd=>{sent.push(cmd);return true},()=>{},()=>{});
 box.enqueue('final',{token:{id:'a',x:3,y:4}});box.reconnect();if(sent.length!==2||sent[0].seq!==sent[1].seq)throw Error('retry identity lost');
 const restored=new Outbox(store,'test',cmd=>{sent.push(cmd);return true},()=>{},()=>{});restored.reconnect();if(sent[2].client!==sent[0].client)throw Error('reload identity lost');restored.ack({seq:1});if(restored.data.queue.length)throw Error('ack did not clear queue');
 const positionStore=new Map(),positionStorage={getItem:k=>positionStore.get(k),setItem:(k,v)=>positionStore.set(k,v)},positionSent=[];
 const positions=new Outbox(positionStorage,'positions',cmd=>{positionSent.push(cmd);return true},()=>{},()=>{});positions.enqueue('final',{token:{id:'a',x:10,y:10}});positions.enqueue('final',{token:{id:'a',x:20,y:20}});if(!positions.hasQueuedBehindInflight())throw Error('queued final did not block preview');positions.ack({seq:1});if(positions.hasQueuedBehindInflight())throw Error('preview remained blocked after queued final was sent');if(positionSent.length!==2||positionSent[1].seq!==2)throw Error('next final was not sent after ack');
 let rejectedCompletion;const rejected=new Outbox(positionStorage,'rejected',()=>true,()=>{},(cmd,error,errorCode)=>{rejectedCompletion={cmd,error,errorCode}});rejected.enqueue('final',{token:{id:'a',x:30,y:30}});rejected.ack({seq:1,error:'blocked',errorCode:'movementBlocked'});if(rejectedCompletion?.errorCode!=='movementBlocked')throw Error('movement rejection code was lost by outbox');const heldDrag={type:'token',id:'a',floorId:'floor',x:30,y:30,networkX:30,networkY:30,pointerDirty:true,moved:true},heldToken={id:'a',floorId:'floor',x:10,y:10},correction=blockedMoveCorrection({operation:'move',errorCode:'movementBlocked',sceneId:'scene',floorId:'floor',id:'a',x:10,y:10},heldDrag,heldToken,'scene');if(!correction||correction.drag===heldDrag||correction.drag.x!==10||correction.drag.networkX!==10||correction.drag.pointerDirty||correction.token.x!==10||blockedMoveCorrection({operation:'other',errorCode:'movementBlocked'},heldDrag,heldToken,'scene')!==null)throw Error('blocked movement did not preserve and reconcile drag');const staleCorrection=blockedMoveCorrection({operation:'move',errorCode:'movementBlocked',sceneId:'old',floorId:'floor',id:'a',x:0,y:0},heldDrag,heldToken,'scene');if(staleCorrection.drag!==heldDrag||staleCorrection.token!==heldToken)throw Error('stale movement correction was applied');
 const d=new Drafts();d.set('a','name','one');d.set('a','name','two');d.confirm('a',{name:'one'});if(d.get('a').name!=='two')throw Error('ack erased newer draft');
 const writes=new CacheWriteBudget(2,10);const releaseA=writes.acquire(6);if(!releaseA||writes.acquire(5)!==null)throw Error('write byte budget');const releaseB=writes.acquire(4);if(!releaseB||writes.acquire(1)!==null)throw Error('write count budget');releaseA();const releaseC=writes.acquire(5);if(!releaseC||writes.bytes!==9)throw Error('write budget release');releaseB();releaseC();if(writes.count||writes.bytes)throw Error('write budget leaked');
 for(const count of [1,64,65,100,1000,2000]){const edge=imageEdge(count,64*1048576);if(count*edge*edge*4>64*1048576)throw Error('image budget exceeded')}
	const perfLayers=Object.fromEntries(Array.from({length:4},(_,i)=>['layer'+i,{id:'layer'+i,floorId:'floor',kind:'visual',order:i,visible:true,opacity:1}])),perfElements=Object.fromEntries(Array.from({length:1000},(_,i)=>['element'+i,{id:'element'+i,name:'Element '+i,floorId:'floor',layerId:'layer'+(i%4),zOrder:i,visible:true,locked:false,opacity:1,assetId:'image',transform:{x:(i%50)*220,y:Math.floor(i/50)*220,width:100,height:100,rotation:i%7}}])),perfCatalog=Object.fromEntries(Object.entries(perfElements).map(([id,element])=>[id,{...element,assetId:''}])),perfState={you:{role:'gm',gm:true},scene:{id:'scene'},floors:{floor:{id:'floor',name:'Floor',order:0,opacity:1,opacityWhenViewedFromBelow:0}},layers:perfLayers,elements:perfElements,elementCatalog:perfCatalog,_catalogVersion:1,tokens:{},transitions:{},assets:{}};let checksum=0,start=performance.now();for(let pass=0;pass<100;pass++)for(const layer of Object.values(perfLayers)){const sorted=Object.values(perfElements).filter(element=>element.layerId===layer.id).sort((a,b)=>a.zOrder-b.zOrder||a.id.localeCompare(b.id));checksum+=sorted.length;}const legacyOrderMs=performance.now()-start,perfIndex=new SceneRenderIndex();for(const layer of Object.values(perfLayers))perfIndex.forLayer(perfState,layer.id);start=performance.now();for(let pass=0;pass<100;pass++)for(const layer of Object.values(perfLayers))checksum+=perfIndex.forLayer(perfState,layer.id).length;const cachedOrderMs=performance.now()-start;
	let focused='',treeCommands=[];const treeElements={tree:document.createElement('div'),addFloor:document.createElement('button'),addLayer:document.createElement('button'),addTransition:document.createElement('button'),controls:[]},treeRuntime=new SceneTreeRuntime(treeElements,{queue:(type,payload)=>treeCommands.push({type,payload}),selectElement:()=>{},selectTransition:()=>{},beginTransition:()=>{},setFloor:()=>{},getFloor:()=> 'floor',focusElement:element=>{focused=element.id;}});start=performance.now();for(let pass=0;pass<20;pass++)treeRuntime.update(perfState,'','');const legacyTreeMs=performance.now()-start,treeNode=treeElements.tree.querySelector('.tree-element-row'),treeRebuilds=treeRuntime.rebuilds;start=performance.now();for(let pass=0;pass<20;pass++){const item=perfState.elements.element0;perfState.elements={...perfState.elements,element0:{...item,transform:{...item.transform,x:item.transform.x+1}}};treeRuntime.update(perfState,pass%2?'element0':'','');}const transformOnlyMs=performance.now()-start;if(treeElements.tree.querySelector('.tree-element-row')!==treeNode||treeRuntime.rebuilds!==treeRebuilds)throw Error('viewport state rebuilt persistent scene tree');treeNode.querySelector('[title="Центрировать на элементе"]').click();if(!focused)throw Error('element focus action missing');treeElements.tree.querySelector('.tree-layer-walkable [title="Показывать непроходимые области игрокам"]').click();const overlayCommand=treeCommands.at(-1);if(overlayCommand?.type!=='floorUpdate'||overlayCommand.payload?.floor?.id!=='floor'||overlayCommand.payload?.floorProperties?.showWalkableToPlayers!==true)throw Error('walkable player visibility action missing');
 const viewport={left:0,top:0,right:1000,bottom:800},visibleBitmaps=Object.values(perfElements).filter(element=>elementIntersectsView(element,viewport)).length;window.optimizationMetrics={legacyOrderMs,cachedOrderMs,legacyTreeMs,transformOnlyMs,legacyTreeRebuilds:20,transformTreeRebuilds:0,legacyBitmapRequests:Object.keys(perfElements).length,culledBitmapRequests:visibleBitmaps,checksum};
 return true;
})()`
