package main

// Served only by the isolated profiling host. The host makes the test copy of
// app.js canvas/context bindings mutable so replacement can be measured without
// changing production app.js before the causal experiment succeeds.
const profileProbe = `
const probe={durations:[],latencies:[],decodes:0,decodeMs:0,closed:0,drawImages:0,peakBitmaps:0,peakBytes:0,lastX:null,timers:[],measuring:false,resetDurations:[],resetFrameGaps:[],resetMeasuring:false,bitmapCreated:0,bitmapCreatedBytes:0,bitmapClosed:0,bitmapClosedBytes:0,liveBitmaps:0};
const bitmapBytes=new WeakMap(),closedBitmaps=new WeakSet();
const originalBitmap=globalThis.createImageBitmap;
globalThis.createImageBitmap=async(...args)=>{const at=performance.now(),result=await originalBitmap(...args),bytes=(result.width||0)*(result.height||0)*4;bitmapBytes.set(result,bytes);probe.bitmapCreated++;probe.bitmapCreatedBytes+=bytes;probe.liveBitmaps++;probe.decodes++;probe.decodeMs+=performance.now()-at;return result};
const originalClose=ImageBitmap.prototype.close;ImageBitmap.prototype.close=function(){probe.closed++;if(!closedBitmaps.has(this)){closedBitmaps.add(this);const bytes=bitmapBytes.get(this)||0;probe.bitmapClosed++;probe.bitmapClosedBytes+=bytes;probe.liveBitmaps=Math.max(0,probe.liveBitmaps-1)}return originalClose.call(this)};
const originalDrawImage=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(...args){if(probe.measuring)probe.drawImages++;return originalDrawImage.apply(this,args)};
const distribution=a=>{const s=[...a].sort((a,b)=>a-b);return {count:s.length,mean:s.reduce((a,b)=>a+b,0)/(s.length||1),p50:s[Math.floor(s.length*.5)]||0,p95:s[Math.floor(s.length*.95)]||0,p99:s[Math.floor(s.length*.99)]||0,max:s.at(-1)||0}};
const startResetFrameMonitor=(previousWall=0)=>{let last=performance.now(),first=true;const tick=now=>{if(!probe.resetMeasuring)return;if(first&&previousWall)probe.resetFrameGaps.push(Math.max(0,Date.now()-previousWall));else probe.resetFrameGaps.push(Math.max(0,now-last));first=false;last=now;probe.resetLastFrameWall=Date.now();requestAnimationFrame(tick)};requestAnimationFrame(tick)};
const originalDraw=draw;draw=function(now){const at=performance.now();originalDraw(now);const elapsed=performance.now()-at;if(probe.measuring)probe.durations.push(elapsed);if(probe.resetMeasuring)probe.resetDurations.push(elapsed);const t=state?.tokens['moving'];if(t&&probe.lastX!==t.x){probe.lastX=t.x;if(probe.latencyOn)probe.latencies.push(((Date.now()%10000)-t.x*10+10000)%10000)}probe.peakBitmaps=Math.max(probe.peakBitmaps,memory.size);probe.peakBytes=Math.max(probe.peakBytes,memoryBytes)};
probe.reset=()=>{probe.durations=[];probe.latencies=[];probe.decodes=0;probe.decodeMs=0;probe.closed=0;probe.drawImages=0;probe.fallbackAt=lodFallbacks;probe.degradeAt=imageDegradations;probe.peakBitmaps=memory.size;probe.peakBytes=memoryBytes;probe.at=performance.now()};
probe.sample=async()=>{const db=await dbPromise;let disk={count:0,bytes:0};if(db)await new Promise(resolve=>{const req=db.transaction('assets').objectStore('assets').openCursor();req.onsuccess=()=>{const c=req.result;if(c){disk.count++;disk.bytes+=c.value.size;c.continue()}else resolve()};req.onerror=resolve});const elapsed=performance.now()-probe.at,frames=probe.durations.length,serialized=state?new Blob([JSON.stringify(state)]).size:0;return {elapsedMs:elapsed,fps:frames/(elapsed/1000),frame:distribution(probe.durations),latency:distribution(probe.latencies),drawImages:probe.drawImages,drawImagesPerFrame:probe.drawImages/(frames||1),bitmaps:memory.size,bitmapBytes:memoryBytes,artworkBytes:typeof artwork==='undefined'?0:artwork.bytes,peakBitmaps:probe.peakBitmaps,peakBitmapBytes:probe.peakBytes,decodeEdge,decodes:probe.decodes,decodeMs:probe.decodeMs,closed:probe.closed,lodFallbacks:lodFallbacks-probe.fallbackAt,degradations:imageDegradations-probe.degradeAt,disk,cacheHits,activeLoads,failures:failures.size,jsHeap:performance.memory?.usedJSHeapSize||0,tokens:Object.keys(state?.tokens||{}).length,elements:Object.keys(state?.elements||{}).length,stateBytes:serialized,queue:(outbox?.data.queue.length||0)+(positionOutbox?.data.queue.length||0),diagnostics:$('diagnostics').textContent}};
probe.stop=()=>{for(const timer of probe.timers)clearInterval(timer);probe.timers=[];$('continuous').checked=false;probe.latencyOn=false;probe.measuring=false};
probe.start=(mode)=>{probe.stop();probe.reset();probe.measuring=true;probe.latencyOn=mode==='receive';if(mode==='render'||mode==='receive'){$('continuous').checked=true;dirty=true}if(mode==='pan'){const began=performance.now();probe.timers.push(setInterval(()=>{const t=(performance.now()-began)/1000;camera.scale=.13+.6*(.5+.5*Math.sin(t*.8));camera.x=1000+1000*Math.sin(t*.4);camera.y=700+700*Math.cos(t*.5);dirty=true},16))}if(mode==='move'){let tick=0;probe.timers.push(setInterval(()=>{const t={id:'moving',x:(Date.now()%10000)/10,y:500};send({type:'move',token:t});if(++tick%20===0)queuePosition({token:t})},50))}};
probe.clearImages=async()=>{await $('clearCache').onclick();return true};
probe.clearDecodedImages=()=>{for(const entry of memory.values()){entry.bitmap.close();entry.fallback?.bitmap.close();}memory.clear();memoryBytes=0;artwork.clear();dirty=true;return probe.lifecycle()};
probe.trimImages=()=>{trimImages();return probe.lifecycle()};
probe.imageMemory=()=>{let bitmapBytesInCache=0,fallbackBytes=0;for(const entry of memory.values()){bitmapBytesInCache+=entry.bitmapSize||0;fallbackBytes+=entry.fallback?.size||0}return {entries:memory.size,trackedBytes:memoryBytes,bitmapBytes:bitmapBytesInCache,fallbackBytes,artworkBytes:typeof artwork==='undefined'?0:artwork.bytes,pending:pending.size,activeLoads,canvasBytes:canvas.width*canvas.height*4,liveBitmaps:probe.liveBitmaps,bitmapCreated:probe.bitmapCreated,bitmapClosed:probe.bitmapClosed,bitmapCloseCalls:probe.closed,bitmapCreatedBytes:probe.bitmapCreatedBytes,bitmapClosedBytes:probe.bitmapClosedBytes,decodeCount,diskReads}};
probe.cacheState=()=>({memoryEntries:memory.size,memoryBytes,diskBytes,diskReads,diskWrites,diskEvictions,diskDrops,cacheHits,tileBytes,decodeCount,bitmapCreated:probe.bitmapCreated,bitmapClosed:probe.bitmapClosed,liveBitmaps:probe.liveBitmaps,activeLoads,pending:pending.size,regionInFlight});
probe.waitCacheWrites=async()=>{await cacheQueue;return probe.cacheState()};
probe.lifecycle=()=>({camera:{x:camera.x,y:camera.y,scale:camera.scale},sceneState:{sceneId:state?.scene?.id||'',sceneRevision:state?.scene?.revision||0,floorId:currentFloorID||'',selectedToken:selected||'',selectedElement:selectedElement||'',selectedTransition:selectedTransition||'',transitionDraftPhase:transitionDraft?.phase||'',tokens:Object.keys(state?.tokens||{}).length,elements:Object.keys(state?.elements||{}).length},canvas:{width:canvas.width,height:canvas.height,viewportWidth:viewport.w,viewportHeight:viewport.h,dpr:viewport.w?canvas.width/viewport.w:0,devicePixelRatio:globalThis.devicePixelRatio||1},images:probe.imageMemory(),resetFrames:distribution(probe.resetFrameGaps),resetDraws:distribution(probe.resetDurations)});
probe.beginReset=()=>{probe.resetDurations=[];probe.resetFrameGaps=[];probe.resetMeasuring=true;probe.resetStartedWall=Date.now();probe.resetLastFrameWall=Date.now();startResetFrameMonitor();return probe.lifecycle()};
probe.prepareReloadReset=()=>{try{sessionStorage.setItem('__atlas-profile-reset',JSON.stringify({startedWall:probe.resetStartedWall||Date.now(),lastFrameWall:probe.resetLastFrameWall||Date.now(),frameGaps:probe.resetFrameGaps,drawDurations:probe.resetDurations}))}catch{}return true};
probe.endReset=()=>{probe.resetMeasuring=false;return {elapsedMs:Date.now()-(probe.resetStartedWall||Date.now()),frame:distribution(probe.resetFrameGaps),draw:distribution(probe.resetDurations)}};
probe.backingReset=()=>{const width=canvas.width,height=canvas.height,at=performance.now();canvas.width=0;canvas.height=0;canvas.width=width;canvas.height=height;dirty=true;draw(performance.now());return {elapsedMs:performance.now()-at,state:probe.lifecycle()}};
probe.replaceCanvas=()=>{const oldCanvas=canvas,width=oldCanvas.width,height=oldCanvas.height,next=document.createElement('canvas');for(const attr of oldCanvas.attributes)next.setAttribute(attr.name,attr.value);next.width=width;next.height=height;const nextCtx=next.getContext('2d');if(!nextCtx)throw Error('2D context replacement failed');const at=performance.now();canvas=next;ctx=nextCtx;dirty=true;draw(performance.now());oldCanvas.replaceWith(next);return {elapsedMs:performance.now()-at,state:probe.lifecycle()}};
probe.memorySweep=()=>{probe.stop();probe.reset();probe.measuring=true;const began=performance.now();probe.timers.push(setInterval(()=>{const bounds=state?.scene?.bounds;if(!bounds)return;const t=(performance.now()-began)/1000,scale=.18+.72*(.5+.5*Math.sin(t*.37)),maxX=Math.max(0,bounds.width-viewport.w/scale),maxY=Math.max(0,bounds.height-viewport.h/scale);camera.scale=scale;camera.x=maxX*(.5+.5*Math.sin(t*.53));camera.y=maxY*(.5+.5*Math.cos(t*.41));dirty=true},16))};
try{const saved=JSON.parse(sessionStorage.getItem('__atlas-profile-reset')||'null');if(saved){sessionStorage.removeItem('__atlas-profile-reset');probe.resetDurations=Array.isArray(saved.drawDurations)?saved.drawDurations:[];probe.resetFrameGaps=Array.isArray(saved.frameGaps)?saved.frameGaps:[];probe.resetStartedWall=Number(saved.startedWall)||Date.now();probe.resetMeasuring=true;startResetFrameMonitor(Number(saved.lastFrameWall)||Date.now())}}catch{}
probe.view=()=>{camera={x:0,y:0,scale:.22};dirty=true};probe.setView=(x,y,scale)=>{camera={x,y,scale};dirty=true;return probe.lifecycle()};probe.enter=c=>enter(c);probe.openScene=id=>openScene(id);probe.home=()=>goCampaignHome();probe.fit=()=>fit();probe.connected=()=>socket?.readyState===1;probe.ready=()=>!!state&&socket?.readyState===1;probe.scene=n=>Object.keys(state?.tokens||{}).length===n;probe.layer=n=>Object.keys(state?.elements||{}).length>=n;probe.layerSettled=n=>probe.layer(n)&&activeLoads===0&&!regionInFlight;probe.layerStatus=()=>({elements:Object.keys(state?.elements||{}).length,activeLoads,regionInFlight});
globalThis.__atlasProbe=probe;
`
